package com.otta.common.domain.model

/**Class generated by using JSON to kotlin data class converter extension*/
data class Sneaker(
    val brand: String,
    val colorway: String,
    val gender: String,
    val id: String,
    val media: Media,
    val name: String,
    val releaseDate: String,
    val retailPrice: Int,
    val shoe: String,
    val styleId: String,
    val title: String,
    val year: Int
)